### ISSUE TITLE
XyMon URL setting

### ISSUE THREAD

**Issue by phaleintx** [ToBeHH/XymonMonitor#1]
Thanks for the App!

One issue.

On modern installs of Xymon The "bb2.html" page has been replaced by the "nongreen.html" page.  When the app tries to access my Xymon install and doesn't find the bb2.html it lists an exception.  Can this be changed?

**Comment by ToBeHH** [comment]
I updated the app. Now you can enter the URL including /nongreen.html and it takes that URL directly.
